/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/care-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist an explicitly confirmed preview */
        post: operations["createCarePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/care-plans/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview a care plan without saving it */
        post: operations["previewCarePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/care-plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a saved care plan */
        get: operations["getCarePlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Pause or activate a care plan */
        patch: operations["updateCarePlan"];
        trace?: never;
    };
    "/v1/care-plans/{plan_id}/tasks/{task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a care task complete */
        post: operations["completeCareTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create up to three recommendations */
        post: operations["createRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream recommendation workflow progress */
        post: operations["streamRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Cadence
         * @enum {string}
         */
        Cadence: "DAILY" | "WEEKLY" | "MONTHLY" | "QUARTERLY" | "ANNUALLY";
        /** CarePlan */
        CarePlan: {
            category: components["schemas"]["Category"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Item Name */
            item_name: string;
            metadata: components["schemas"]["RequestMetadata"];
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Recommendation Id */
            recommendation_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["CarePlanStatus"];
            /** Tasks */
            tasks: components["schemas"]["CareTask"][];
            /** Timezone */
            timezone: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** CarePlanCreateRequest */
        CarePlanCreateRequest: {
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
            /**
             * Preview Id
             * Format: uuid
             */
            preview_id: string;
        };
        /** CarePlanPreviewRequest */
        CarePlanPreviewRequest: {
            category: components["schemas"]["Category"];
            /** Item Name */
            item_name: string;
            /** Recommendation Id */
            recommendation_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Timezone */
            timezone: string;
        };
        /** CarePlanPreviewResponse */
        CarePlanPreviewResponse: {
            category: components["schemas"]["Category"];
            /**
             * Confirmation Required
             * @default true
             * @constant
             */
            confirmation_required: true;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Item Name */
            item_name: string;
            metadata: components["schemas"]["RequestMetadata"];
            /**
             * Preview Id
             * Format: uuid
             */
            preview_id: string;
            /** Recommendation Id */
            recommendation_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Tasks */
            tasks: components["schemas"]["CareTask"][];
            /** Timezone */
            timezone: string;
        };
        /**
         * CarePlanStatus
         * @enum {string}
         */
        CarePlanStatus: "ACTIVE" | "PAUSED";
        /** CarePlanUpdateRequest */
        CarePlanUpdateRequest: {
            status: components["schemas"]["CarePlanStatus"];
        };
        /** CareTask */
        CareTask: {
            cadence: components["schemas"]["Cadence"];
            /** Completed At */
            completed_at?: string | null;
            /** Instructions */
            instructions: string;
            /**
             * Next Due On
             * Format: date
             */
            next_due_on: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Title */
            title: string;
        };
        /** CatQuestionnaire */
        CatQuestionnaire: {
            /**
             * Activity Level
             * @enum {string}
             */
            activity_level: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Affection Preference
             * @enum {string}
             */
            affection_preference: "INDEPENDENT" | "BALANCED" | "AFFECTIONATE";
            /**
             * Children Present
             * @default false
             */
            children_present: boolean;
            /** Existing Pets */
            existing_pets?: ("DOG" | "CAT")[];
            /**
             * Experience
             * @enum {string}
             */
            experience: "BEGINNER" | "INTERMEDIATE" | "EXPERT";
            /**
             * Grooming Tolerance
             * @enum {string}
             */
            grooming_tolerance: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Home Size
             * @enum {string}
             */
            home_size: "SMALL" | "MEDIUM" | "LARGE";
            /** Hours Alone */
            hours_alone: number;
            /**
             * Housing Type
             * @enum {string}
             */
            housing_type: "APARTMENT" | "CONDO" | "HOUSE";
            /** Monthly Budget */
            monthly_budget: number;
            /**
             * Outdoor Space
             * @enum {string}
             */
            outdoor_space: "NONE" | "BALCONY" | "YARD";
            /** Rental Allows Pets */
            rental_allows_pets: boolean;
        };
        /** CatRecommendationRequest */
        CatRecommendationRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            category: "CAT";
            destination: components["schemas"]["Destination"];
            questionnaire: components["schemas"]["CatQuestionnaire"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Use Saved Preferences
             * @default false
             */
            use_saved_preferences: boolean;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "PLANT" | "DOG" | "CAT";
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "CONFIRMED" | "RECENTLY_OBSERVED" | "UNVERIFIED";
        /** CostEstimate */
        CostEstimate: {
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Initial Max */
            initial_max: number;
            /** Initial Min */
            initial_min: number;
            /** Monthly Max */
            monthly_max: number;
            /** Monthly Min */
            monthly_min: number;
        };
        /** Destination */
        Destination: {
            /** State Code */
            state_code?: string | null;
            /**
             * Zip Code
             * @example 10001
             */
            zip_code: string;
        };
        /** DogRecommendationRequest */
        DogRecommendationRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            category: "DOG";
            destination: components["schemas"]["Destination"];
            questionnaire: components["schemas"]["PetQuestionnaire"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Use Saved Preferences
             * @default false
             */
            use_saved_preferences: boolean;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Details */
            details?: components["schemas"]["ErrorDetail"][];
            /** Message */
            message: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /**
             * Field
             * @default null
             */
            field: string | null;
            /** Message */
            message: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EvidenceReference */
        EvidenceReference: {
            /** Content Version */
            content_version: string;
            /** Evidence Id */
            evidence_id: string;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /** Source Name */
            source_name: string;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string;
        };
        /** LocalSource */
        LocalSource: {
            confidence: components["schemas"]["Confidence"];
            /**
             * Distance Miles
             * @default null
             */
            distance_miles: number | null;
            /** Name */
            name: string;
            /** Source Type */
            source_type: string;
            /** Url */
            url: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
        };
        /** PetQuestionnaire */
        PetQuestionnaire: {
            /**
             * Activity Level
             * @enum {string}
             */
            activity_level: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Children Present
             * @default false
             */
            children_present: boolean;
            /** Existing Pets */
            existing_pets?: ("DOG" | "CAT")[];
            /**
             * Experience
             * @enum {string}
             */
            experience: "BEGINNER" | "INTERMEDIATE" | "EXPERT";
            /**
             * Grooming Tolerance
             * @enum {string}
             */
            grooming_tolerance: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Home Size
             * @enum {string}
             */
            home_size: "SMALL" | "MEDIUM" | "LARGE";
            /** Hours Alone */
            hours_alone: number;
            /**
             * Housing Type
             * @enum {string}
             */
            housing_type: "APARTMENT" | "CONDO" | "HOUSE";
            /** Monthly Budget */
            monthly_budget: number;
            /**
             * Outdoor Space
             * @enum {string}
             */
            outdoor_space: "NONE" | "BALCONY" | "YARD";
            /** Rental Allows Pets */
            rental_allows_pets: boolean;
        };
        /** PlantQuestionnaire */
        PlantQuestionnaire: {
            /**
             * Available Space
             * @enum {string}
             */
            available_space: "SMALL" | "MEDIUM" | "LARGE";
            /**
             * Children Present
             * @default false
             */
            children_present: boolean;
            /**
             * Experience
             * @enum {string}
             */
            experience: "BEGINNER" | "INTERMEDIATE" | "EXPERT";
            /**
             * Humidity
             * @enum {string}
             */
            humidity: "LOW" | "AVERAGE" | "HIGH";
            /** Indoor Temperature F */
            indoor_temperature_f: number;
            /**
             * Light Level
             * @enum {string}
             */
            light_level: "LOW" | "MEDIUM" | "BRIGHT_INDIRECT" | "DIRECT";
            /** Monthly Budget */
            monthly_budget: number;
            /** Pets Present */
            pets_present?: ("DOG" | "CAT")[];
            /**
             * Watering Availability
             * @enum {string}
             */
            watering_availability: "LOW" | "MEDIUM" | "HIGH";
        };
        /** PlantRecommendationRequest */
        PlantRecommendationRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            category: "PLANT";
            destination: components["schemas"]["Destination"];
            questionnaire: components["schemas"]["PlantQuestionnaire"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Use Saved Preferences
             * @default false
             */
            use_saved_preferences: boolean;
        };
        /** ProgressData */
        ProgressData: {
            /** Message */
            message: string;
            /** Percent */
            percent: number;
            stage: components["schemas"]["ProgressStage"];
        };
        /** @enum {string} */
        ProgressStage: "ACCEPTED" | "VALIDATING" | "APPLYING_SAFETY" | "SCORING" | "EVALUATING" | "OPTIMIZING";
        /** RecommendationCompletedEvent */
        RecommendationCompletedEvent: {
            data: components["schemas"]["RecommendationResponse"];
            /**
             * Emitted At
             * Format: date-time
             */
            emitted_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "completed";
            /** Event Id */
            event_id: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            /** Sequence */
            sequence: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** RecommendationFailedEvent */
        RecommendationFailedEvent: {
            data: components["schemas"]["ErrorBody"];
            /**
             * Emitted At
             * Format: date-time
             */
            emitted_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "failed";
            /** Event Id */
            event_id: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            /** Sequence */
            sequence: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Best Match */
            best_match: boolean;
            /** Care Summary */
            care_summary: string[];
            /** Concerns */
            concerns?: string[];
            cost: components["schemas"]["CostEstimate"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceReference"][];
            /** Local Sources */
            local_sources?: components["schemas"]["LocalSource"][];
            /** Name */
            name: string;
            /** Profile */
            profile: string;
            /** Reasons */
            reasons: string[];
            /** Recommendation Id */
            recommendation_id: string;
            safety: components["schemas"]["SafetyDisclosure"];
            /**
             * Scientific Name
             * @default null
             */
            scientific_name: string | null;
            /** Score */
            score: number;
        };
        /** RecommendationProgressEvent */
        RecommendationProgressEvent: {
            data: components["schemas"]["ProgressData"];
            /**
             * Emitted At
             * Format: date-time
             */
            emitted_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "progress";
            /** Event Id */
            event_id: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Schema Version
             * @default v1
             * @constant
             */
            schema_version: "v1";
            /** Sequence */
            sequence: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            category: components["schemas"]["Category"];
            metadata: components["schemas"]["RequestMetadata"];
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationItem"][];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            validation_status: components["schemas"]["ValidationStatus"];
            /** Warnings */
            warnings?: string[];
        };
        RecommendationStreamEvent: components["schemas"]["RecommendationProgressEvent"] | components["schemas"]["RecommendationCompletedEvent"] | components["schemas"]["RecommendationFailedEvent"];
        /** RequestMetadata */
        RequestMetadata: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            versions: components["schemas"]["VersionInfo"];
        };
        /** SafetyDisclosure */
        SafetyDisclosure: {
            /**
             * Cat Toxicity
             * @enum {string}
             */
            cat_toxicity: "TOXIC" | "NON_TOXIC" | "UNKNOWN" | "NOT_APPLICABLE";
            /**
             * Child Toxicity
             * @enum {string}
             */
            child_toxicity: "TOXIC" | "NON_TOXIC" | "UNKNOWN" | "NOT_APPLICABLE";
            /**
             * Dog Toxicity
             * @enum {string}
             */
            dog_toxicity: "TOXIC" | "NON_TOXIC" | "UNKNOWN" | "NOT_APPLICABLE";
            /**
             * Hard Constraints Passed
             * @default true
             * @constant
             */
            hard_constraints_passed: true;
        };
        /**
         * ValidationStatus
         * @enum {string}
         */
        ValidationStatus: "PASSED" | "DEGRADED";
        /** VersionInfo */
        VersionInfo: {
            /**
             * Api
             * @default v1
             */
            api: string;
            /**
             * Graph
             * @default recommendation-graph-v1
             */
            graph: string;
            /**
             * Knowledge
             * @default fake-catalog-v1
             */
            knowledge: string;
            /**
             * Model
             * @default none
             */
            model: string;
            /**
             * Prompt
             * @default deterministic-explanations-v1
             */
            prompt: string;
            /**
             * Rules
             * @default rules-v1
             */
            rules: string;
            /**
             * Scoring
             * @default scoring-v1
             */
            scoring: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCarePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarePlanCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarePlan"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation or eligibility failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    previewCarePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarePlanPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarePlanPreviewResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation or eligibility failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCarePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarePlan"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation or eligibility failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    updateCarePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarePlanUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarePlan"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation or eligibility failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    completeCareTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarePlan"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation or eligibility failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlantRecommendationRequest"] | components["schemas"]["DogRecommendationRequest"] | components["schemas"]["CatRecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation or eligibility failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    streamRecommendation: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlantRecommendationRequest"] | components["schemas"]["DogRecommendationRequest"] | components["schemas"]["CatRecommendationRequest"];
            };
        };
        responses: {
            /** @description Versioned recommendation progress events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["RecommendationStreamEvent"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description State conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation or eligibility failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
